version: '3.3'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - '4566:4566'
    environment:
      - SERVICES=dynamodb
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
